### ISSUE TITLE
Files are not merged properly

### ISSUE THREAD

**Issue by wheatdog** [chr-1x/4vim#2]
I want to try 4vim, but I think files are not properly merged right now.

**Comment by chr-1x** [comment]
Yeah, I'm aware of this. I should have put something in the description. I'll be going through and fixing this, as well as updating the plugin to the latest 4coder version, within the next week or so.

**Comment by wheatdog** [comment]
I would like to help, but I am a 4coder newbie. Is there any recommend site/documentation to learn 4coder customize API?

**Comment by chr-1x** [comment]
Allen provides a documentation HTML file with each build of 4coder he posts to his patreon. That'd be one place to start. Beyond that there's not too many resources as of now other than just reading the example custom he provides and seeing what the API looks like in use.

4vim now building again, closing this issue.
